[package]
name = "overloaded_literals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
const_format = "0.2.30"
tlist = "0.6.2"
overloaded_literals_macro = { path = "../overloaded_literals_macro" }
proc-macro2 = "1.0.56"
typenum = "1.16.0"
generic-array = "0.14.7"
uuid = "1.3.0"

[dev-dependencies]
const-str = "0.5.4"