name: Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test
    #- name: Test --no-default-features
    #  run: cargo test --no-default-features --verbose
    #- name: Test --all-features
    #  run: cargo test --all-features --verbose
